-- DDL (DATA DEFINITION LANGUAGE)
-- CREATE DATABASE
CREATE DATABASE COLLEGE;
USE COLLEGE;

-- CREATE TABLE
CREATE TABLE STUDENTS
(
ID VARCHAR(10),
NAME VARCHAR(50),
MARKS INT
);

-- DROP TABLE AND DATABASE
DROP TABLE STUDENTS;
DROP DATABASE COLLEGE;

-- ALTER TABLE 
ALTER TABLE STUDENTS ADD COLUMN GRADE VARCHAR(10);
ALTER TABLE STUDENTS MODIFY COLUMN GRADE VARCHAR(5);
ALTER TABLE STUDENTS DROP COLUMN GRADE;
ALTER TABLE STUDENTS RENAME STUDENTS_DETAILS;
ALTER TABLE STUDENTS_DETAILS CHANGE MARKS MARK INT;

-- TRUNCATE TABLE
TRUNCATE STUDENTS_DETAILS;

-- DML (DATA MANIPULATION LANGUAGE)
-- INSERTS RECORDS 
INSERT INTO STUDENTS_DETAILS(ID,NAME,MARK) VALUES("D001","KISHORE",87);
INSERT INTO STUDENTS_DETAILS(ID,NAME,MARK) VALUES("D002","VIJAY",94);
INSERT INTO STUDENTS_DETAILS(ID,NAME,MARK) VALUES("D003","ARAVIND",70);

-- UPADATE TABLE RECORDS
SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENTS_DETAILS SET MARK = 83 WHERE ID = "D001";

-- DELETE RECORDS IN TABLE 
DELETE FROM STUDENTS_DETAILS WHERE ID = "D001";
DELETE FROM STUDENTS_DETAILS;

-- DQL (DATA QUERY LANGUAGE)
SELECT * FROM STUDENTS_DETAILS;